// navdash: personal service portal with native OIDC (authorization code + PKCE)
// login and a static card grid generated at Nix evaluation time.
//
// Configuration is read from the environment (see config()):
//
//	NAVDASH_LISTEN           listen address (default 127.0.0.1:13828)
//	NAVDASH_BASE_URL         public origin, e.g. https://nav.zhyi.xin
//	NAVDASH_OIDC_ISSUER      OIDC issuer, e.g. https://login.zhyi.xin
//	NAVDASH_OIDC_CLIENT_ID   client id registered at the issuer
//	NAVDASH_OIDC_CLIENT_SECRET  client secret
//	NAVDASH_SESSION_KEY      hex HMAC key for signed stateless cookies
//	NAVDASH_ALLOWED_USERS    optional comma separated allowlist of
//	                        preferred_username values
//	NAVDASH_ENTRIES          path to entries.json generated by Nix
package main

import (
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"embed"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"log"
	"net/http"
	"net/url"
	"os"
	"strings"
	"sync"
	"time"
)

//go:embed web
var webFS embed.FS

// ---------------------------------------------------------------------------
// Configuration

type config struct {
	listen       string
	baseURL      *url.URL
	issuer       string
	clientID     string
	clientSecret string
	sessionKey   []byte
	allowedUsers map[string]bool
	entriesPath  string
}

func envOr(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

func loadConfig() (*config, error) {
	c := &config{
		listen:       envOr("NAVDASH_LISTEN", "127.0.0.1:13828"),
		issuer:       strings.TrimRight(envOr("NAVDASH_OIDC_ISSUER", ""), "/"),
		clientID:     os.Getenv("NAVDASH_OIDC_CLIENT_ID"),
		clientSecret: os.Getenv("NAVDASH_OIDC_CLIENT_SECRET"),
		entriesPath:  envOr("NAVDASH_ENTRIES", "entries.json"),
	}
	raw := envOr("NAVDASH_BASE_URL", "http://"+c.listen)
	u, err := url.Parse(raw)
	if err != nil {
		return nil, fmt.Errorf("NAVDASH_BASE_URL: %w", err)
	}
	c.baseURL = u
	if c.issuer == "" || c.clientID == "" || c.clientSecret == "" {
		return nil, errors.New("NAVDASH_OIDC_ISSUER / CLIENT_ID / CLIENT_SECRET are required")
	}
	keyHex := os.Getenv("NAVDASH_SESSION_KEY")
	if keyHex == "" {
		return nil, errors.New("NAVDASH_SESSION_KEY is required")
	}
	c.sessionKey, err = hex.DecodeString(keyHex)
	if err != nil {
		return nil, fmt.Errorf("NAVDASH_SESSION_KEY: %w", err)
	}
	if len(c.sessionKey) < 32 {
		return nil, errors.New("NAVDASH_SESSION_KEY must be at least 32 bytes of hex")
	}
	c.allowedUsers = map[string]bool{}
	if v := os.Getenv("NAVDASH_ALLOWED_USERS"); v != "" {
		for _, name := range strings.Split(v, ",") {
			if name = strings.TrimSpace(name); name != "" {
				c.allowedUsers[name] = true
			}
		}
	}
	return c, nil
}

// ---------------------------------------------------------------------------
// Signed cookie helpers (stateless HMAC-SHA256 tokens)

const (
	sessionCookie = "navdash_session"
	txCookie      = "navdash_oidc_tx"
	sessionTTL    = 7 * 24 * time.Hour
	txTTL         = 10 * time.Minute
)

func sign(key, payload []byte) string {
	m := hmac.New(sha256.New, key)
	m.Write(payload)
	return hex.EncodeToString(m.Sum(nil))
}

func seal(key []byte, v any) (string, error) {
	payload, err := json.Marshal(v)
	if err != nil {
		return "", err
	}
	b64 := base64.RawURLEncoding.EncodeToString(payload)
	return b64 + "." + sign(key, []byte(b64)), nil
}

func unseal(key []byte, cookie string, v any) error {
	b64, sig, ok := strings.Cut(cookie, ".")
	if !ok {
		return errors.New("malformed token")
	}
	expect := sign(key, []byte(b64))
	if subtle.ConstantTimeCompare([]byte(sig), []byte(expect)) != 1 {
		return errors.New("bad signature")
	}
	payload, err := base64.RawURLEncoding.DecodeString(b64)
	if err != nil {
		return err
	}
	return json.Unmarshal(payload, v)
}

type session struct {
	User    string `json:"u"`
	Email   string `json:"e"`
	Subject string `json:"sub"`
	Expire  int64  `json:"exp"`
}

func (s session) valid() bool {
	return time.Now().Unix() < s.Expire
}

// tx carries the OIDC state / PKCE verifier between login and callback,
// bound to the browser via a short lived signed cookie.
type tx struct {
	State    string `json:"state"`
	Verifier string `json:"verifier"`
	Expire   int64  `json:"exp"`
}

func setCookie(w http.ResponseWriter, name, value string, ttl time.Duration) {
	http.SetCookie(w, &http.Cookie{
		Name:     name,
		Value:    value,
		Path:     "/",
		MaxAge:   int(ttl.Seconds()),
		Expires:  time.Now().Add(ttl),
		HttpOnly: true,
		Secure:   true,
		SameSite: http.SameSiteLaxMode,
	})
}

func clearCookie(w http.ResponseWriter, name string) {
	http.SetCookie(w, &http.Cookie{
		Name: name, Value: "", Path: "/", MaxAge: -1,
		HttpOnly: true, Secure: true, SameSite: http.SameSiteLaxMode,
	})
}

func (a *app) currentSession(r *http.Request) (session, bool) {
	ck, err := r.Cookie(sessionCookie)
	if err != nil {
		return session{}, false
	}
	var s session
	if unseal(a.cfg.sessionKey, ck.Value, &s) != nil || !s.valid() {
		return session{}, false
	}
	return s, true
}

// ---------------------------------------------------------------------------
// OIDC discovery (lazy, cached, retried on demand)

type endpoints struct {
	Authorization string `json:"authorization_endpoint"`
	Token         string `json:"token_endpoint"`
	UserInfo      string `json:"userinfo_endpoint"`
}

func (a *app) discover() (*endpoints, error) {
	a.discMu.Lock()
	defer a.discMu.Unlock()
	if a.disc != nil {
		return a.disc, nil
	}
	url := a.cfg.issuer + "/.well-known/openid-configuration"
	resp, err := a.client.Get(url)
	if err != nil {
		return nil, fmt.Errorf("discovery: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("discovery: status %d", resp.StatusCode)
	}
	var ep endpoints
	if err := json.NewDecoder(resp.Body).Decode(&ep); err != nil {
		return nil, fmt.Errorf("discovery: %w", err)
	}
	a.disc = &ep
	return a.disc, nil
}

// ---------------------------------------------------------------------------
// Entries (generated at Nix evaluation time)

type entry struct {
	Name      string `json:"name"`
	Highlight string `json:"highlight"`
	Suffix    string `json:"suffix"`
	Proto     string `json:"proto"`
	URL       string `json:"url"`
	Host      string `json:"host"`
	Access    string `json:"access"`
}

type entryFile struct {
	Entries []entry `json:"entries"`
}

func loadEntries(path string) (entryFile, error) {
	var ef entryFile
	raw, err := os.ReadFile(path)
	if err != nil {
		return ef, err
	}
	if err := json.Unmarshal(raw, &ef); err != nil {
		return ef, fmt.Errorf("parse %s: %w", path, err)
	}
	return ef, nil
}

// ---------------------------------------------------------------------------
// Application

type app struct {
	cfg    *config
	client *http.Client
	disc   *endpoints
	discMu sync.Mutex

	entriesMu sync.RWMutex
	entries   entryFile

	probe *prober

	icons     *iconStore
	iconHosts map[string]bool
	bg        *bgStore

	staticFS fs.FS
	etags    map[string]string
}

func newApp(cfg *config) (*app, error) {
	ef, err := loadEntries(cfg.entriesPath)
	if err != nil {
		return nil, err
	}
	sub, err := fs.Sub(webFS, "web")
	if err != nil {
		return nil, err
	}
	a := &app{
		cfg:       cfg,
		client:    &http.Client{Timeout: 15 * time.Second},
		entries:   ef,
		probe:     newProber(probeInterval()),
		icons:     newIconStore(),
		iconHosts: map[string]bool{},
		bg:        newBGStore(),
		staticFS:  sub,
		etags:     map[string]string{},
	}
	for _, h := range entryHosts(ef.Entries) {
		a.iconHosts[h] = true
	}
	a.buildEtags()
	go a.probe.loop(ef.Entries)
	go a.icons.prefetch(entryHosts(ef.Entries))
	// Warm the hero background so the first visitor doesn't pay the fetch.
	go func() { a.bg.get() }()
	return a, nil
}

func (a *app) buildEtags() {
	_ = fs.WalkDir(a.staticFS, ".", func(p string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return nil
		}
		raw, err := fs.ReadFile(a.staticFS, p)
		if err != nil {
			return nil
		}
		sum := sha256.Sum256(raw)
		a.etags["/"+p] = `"` + hex.EncodeToString(sum[:16]) + `"`
		return nil
	})
}

// ---------------------------------------------------------------------------
// OIDC handlers

func randomHex(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

func (a *app) handleLogin(w http.ResponseWriter, r *http.Request) {
	ep, err := a.discover()
	if err != nil {
		log.Printf("login: %v", err)
		http.Error(w, "OIDC provider unavailable", http.StatusBadGateway)
		return
	}
	state, err := randomHex(16)
	if err != nil {
		http.Error(w, "internal error", http.StatusInternalServerError)
		return
	}
	verifier, err := randomHex(32)
	if err != nil {
		http.Error(w, "internal error", http.StatusInternalServerError)
		return
	}
	// S256 code challenge
	sum := sha256.Sum256([]byte(verifier))
	challenge := base64.RawURLEncoding.EncodeToString(sum[:])

	token, err := seal(a.cfg.sessionKey, tx{
		State: state, Verifier: verifier, Expire: time.Now().Add(txTTL).Unix(),
	})
	if err != nil {
		http.Error(w, "internal error", http.StatusInternalServerError)
		return
	}
	setCookie(w, txCookie, token, txTTL)

	q := url.Values{}
	q.Set("response_type", "code")
	q.Set("client_id", a.cfg.clientID)
	q.Set("redirect_uri", a.cfg.baseURL.JoinPath("/auth/callback").String())
	q.Set("scope", "openid profile email")
	q.Set("state", state)
	q.Set("code_challenge", challenge)
	q.Set("code_challenge_method", "S256")
	http.Redirect(w, r, ep.Authorization+"?"+q.Encode(), http.StatusFound)
}

type tokenResponse struct {
	AccessToken string `json:"access_token"`
	IDToken     string `json:"id_token"`
	TokenType   string `json:"token_type"`
}

type userInfoResponse struct {
	Subject       string `json:"sub"`
	PreferredUser string `json:"preferred_username"`
	Email         string `json:"email"`
}

func (a *app) handleCallback(w http.ResponseWriter, r *http.Request) {
	fail := func(msg string, code int) {
		clearCookie(w, txCookie)
		http.Error(w, msg, code)
	}
	if errStr := r.URL.Query().Get("error"); errStr != "" {
		fail("login failed: "+errStr, http.StatusUnauthorized)
		return
	}
	code := r.URL.Query().Get("code")
	state := r.URL.Query().Get("state")
	if code == "" || state == "" {
		fail("missing code/state", http.StatusBadRequest)
		return
	}
	ck, err := r.Cookie(txCookie)
	if err != nil {
		fail("login session expired, retry", http.StatusBadRequest)
		return
	}
	var t tx
	if unseal(a.cfg.sessionKey, ck.Value, &t) != nil || time.Now().Unix() > t.Expire {
		fail("login session invalid, retry", http.StatusBadRequest)
		return
	}
	if subtle.ConstantTimeCompare([]byte(t.State), []byte(state)) != 1 {
		fail("state mismatch", http.StatusBadRequest)
		return
	}
	clearCookie(w, txCookie)

	ep, err := a.discover()
	if err != nil {
		fail("OIDC provider unavailable", http.StatusBadGateway)
		return
	}
	redirectURI := a.cfg.baseURL.JoinPath("/auth/callback").String()
	form := url.Values{
		"grant_type":    {"authorization_code"},
		"code":          {code},
		"redirect_uri":  {redirectURI},
		"client_id":     {a.cfg.clientID},
		"client_secret": {a.cfg.clientSecret},
		"code_verifier": {t.Verifier},
	}
	tresp, err := a.client.PostForm(ep.Token, form)
	if err != nil {
		log.Printf("token exchange: %v", err)
		fail("token exchange failed", http.StatusBadGateway)
		return
	}
	defer tresp.Body.Close()
	if tresp.StatusCode != http.StatusOK {
		log.Printf("token exchange: status %d", tresp.StatusCode)
		fail("token exchange failed", http.StatusBadGateway)
		return
	}
	var tr tokenResponse
	if err := json.NewDecoder(tresp.Body).Decode(&tr); err != nil || tr.AccessToken == "" {
		fail("malformed token response", http.StatusBadGateway)
		return
	}

	ureq, _ := http.NewRequest(http.MethodGet, ep.UserInfo, nil)
	ureq.Header.Set("Authorization", "Bearer "+tr.AccessToken)
	uresp, err := a.client.Do(ureq)
	if err != nil {
		log.Printf("userinfo: %v", err)
		fail("userinfo failed", http.StatusBadGateway)
		return
	}
	defer uresp.Body.Close()
	if uresp.StatusCode != http.StatusOK {
		log.Printf("userinfo: status %d", uresp.StatusCode)
		fail("userinfo failed", http.StatusBadGateway)
		return
	}
	var ui userInfoResponse
	if err := json.NewDecoder(uresp.Body).Decode(&ui); err != nil || ui.Subject == "" {
		fail("malformed userinfo", http.StatusBadGateway)
		return
	}

	if len(a.cfg.allowedUsers) > 0 && !a.cfg.allowedUsers[ui.PreferredUser] {
		log.Printf("login denied for %q (not in allowlist)", ui.PreferredUser)
		fail("user not allowed", http.StatusForbidden)
		return
	}

	token, err := seal(a.cfg.sessionKey, session{
		User: ui.PreferredUser, Email: ui.Email, Subject: ui.Subject,
		Expire: time.Now().Add(sessionTTL).Unix(),
	})
	if err != nil {
		fail("internal error", http.StatusInternalServerError)
		return
	}
	setCookie(w, sessionCookie, token, sessionTTL)
	log.Printf("login ok: user=%q sub=%q", ui.PreferredUser, ui.Subject)
	http.Redirect(w, r, "/", http.StatusFound)
}

func (a *app) handleLogout(w http.ResponseWriter, r *http.Request) {
	clearCookie(w, sessionCookie)
	http.Redirect(w, r, "/", http.StatusFound)
}

// ---------------------------------------------------------------------------
// API handlers

func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Cache-Control", "no-store")
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}

func (a *app) handleMe(w http.ResponseWriter, r *http.Request) {
	if s, ok := a.currentSession(r); ok {
		writeJSON(w, http.StatusOK, map[string]any{
			"authenticated": true, "username": s.User, "email": s.Email,
		})
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"authenticated": false})
}

// handleEntries serves the service card list. Unauthenticated visitors only
// see the root domain (https://zhyi.xin, the public blog); authenticated
// sessions get the full list (public + private + localhost services).
func (a *app) handleEntries(w http.ResponseWriter, r *http.Request) {
	_, authed := a.currentSession(r)
	a.entriesMu.RLock()
	entries := a.entries.Entries
	a.entriesMu.RUnlock()
	out := make([]entry, 0, len(entries))
	for _, e := range entries {
		if !authed {
			if e.Access != "public" || e.URL != "https://zhyi.xin" {
				continue
			}
		}
		out = append(out, e)
	}
	writeJSON(w, http.StatusOK, map[string]any{"entries": out})
}

// handleStatus serves the cached health probe results, filtered to exactly
// the entries the requester can see (anonymous visitors get the root blog
// only, same as /api/entries).
func (a *app) handleStatus(w http.ResponseWriter, r *http.Request) {
	_, authed := a.currentSession(r)
	all := a.probe.snapshot()
	if authed {
		writeJSON(w, http.StatusOK, map[string]any{"status": all})
		return
	}
	out := map[string]*probeStatus{}
	if st, ok := all["https://zhyi.xin"]; ok {
		out["https://zhyi.xin"] = st
	}
	writeJSON(w, http.StatusOK, map[string]any{"status": out})
}

// ---------------------------------------------------------------------------
// Static assets

var contentTypes = map[string]string{
	".html":  "text/html; charset=utf-8",
	".css":   "text/css; charset=utf-8",
	".js":    "text/javascript; charset=utf-8",
	".svg":   "image/svg+xml",
	".png":   "image/png",
	".woff2": "font/woff2",
	".txt":   "text/plain; charset=utf-8",
}

func (a *app) handleStatic(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet && r.Method != http.MethodHead {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	p := strings.TrimPrefix(r.URL.Path, "/")
	if p == "" {
		p = "index.html"
	}
	raw, err := fs.ReadFile(a.staticFS, p)
	if err != nil {
		http.NotFound(w, r)
		return
	}
	if etag, ok := a.etags["/"+p]; ok {
		w.Header().Set("ETag", etag)
		if r.Header.Get("If-None-Match") == etag {
			w.WriteHeader(http.StatusNotModified)
			return
		}
	}
	ext := ""
	if i := strings.LastIndex(p, "."); i >= 0 {
		ext = p[i:]
	}
	if ct, ok := contentTypes[ext]; ok {
		w.Header().Set("Content-Type", ct)
	}
	w.Header().Set("Referrer-Policy", "no-referrer")
	if ext == ".html" {
		// The page loads no third-party anything: scripts, styles, fonts,
		// icons and APIs are all same-origin (the theme bootstrap lives in
		// /assets/js/theme-init.js so no inline script is needed).
		w.Header().Set("Content-Security-Policy",
			"default-src 'none'; script-src 'self'; style-src 'self'; "+
				"img-src 'self' data:; font-src 'self'; connect-src 'self'; "+
				"base-uri 'none'; frame-ancestors 'none'; form-action 'self'")
	}
	if p == "index.html" || ext == ".js" || ext == ".css" {
		// Deploy correctness: HTML/JS/CSS changes must be picked up on the
		// next visit. The strong ETag keeps revalidation cheap (304 when
		// unchanged); fonts and images are more stable and cache for a day.
		w.Header().Set("Cache-Control", "no-cache")
	} else {
		w.Header().Set("Cache-Control", "public, max-age=86400")
	}
	w.Header().Set("X-Content-Type-Options", "nosniff")
	_, _ = w.Write(raw)
}

// ---------------------------------------------------------------------------
// Wiring

func (a *app) routes() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("/healthz", func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("ok"))
	})
	mux.HandleFunc("/auth/login", a.handleLogin)
	mux.HandleFunc("/auth/callback", a.handleCallback)
	mux.HandleFunc("/auth/logout", a.handleLogout)
	mux.HandleFunc("/api/me", a.handleMe)
	mux.HandleFunc("/api/entries", a.handleEntries)
	mux.HandleFunc("/api/status", a.handleStatus)
	mux.HandleFunc("/api/icon", a.handleIcon)
	mux.HandleFunc("/api/bg", a.handleBG)
	mux.HandleFunc("/", a.handleStatic)
	return logRequests(mux)
}

type statusWriter struct {
	http.ResponseWriter
	status int
}

func (w *statusWriter) WriteHeader(code int) {
	w.status = code
	w.ResponseWriter.WriteHeader(code)
}

func logRequests(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		sw := &statusWriter{ResponseWriter: w, status: http.StatusOK}
		start := time.Now()
		next.ServeHTTP(sw, r)
		log.Printf("%s %s %d %s %s", r.Method, r.URL.Path, sw.status, time.Since(start), r.RemoteAddr)
	})
}

func main() {
	cfg, err := loadConfig()
	if err != nil {
		log.Fatal(err)
	}
	a, err := newApp(cfg)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("navdash listening on %s (base %s, issuer %s, %d entries)",
		cfg.listen, cfg.baseURL, cfg.issuer, len(a.entries.Entries))
	server := &http.Server{
		Addr:              cfg.listen,
		Handler:           a.routes(),
		ReadHeaderTimeout: 10 * time.Second,
		ReadTimeout:       30 * time.Second,
		WriteTimeout:      30 * time.Second,
		IdleTimeout:       120 * time.Second,
	}
	log.Fatal(server.ListenAndServe())
}
